spring:
  profiles: dev
  h2:
    # 앱 실행하고 localho2:8080/h2로 접속하면 웹 DB 인터페이스 사용 가능하게 설정.
    console:
      enabled: true
      path: /h2

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    # 접속을 위한 드라이버. 역할이 뭐임?
    driver-class-name: org.h2.Driver
    # 설치된 H2 DB와 연결 URL
    url: jdbc:h2:mem:testdb
    # springboot 2.4 부터는 username이 꼭 있어야합니다. 없으면 에러가 발생합니다.

  jpa:
    # 쿼리 날릴 때 console에 sql 보여주기 위한 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

cloud:
  aws:
    credentials:
      access-key: AKIA5TB26NOSKQ3Z4UEJ
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: woostagram
    stack:
      auto: false

logging:
  level:
    com.seungwooryu.woostagram: DEBUG
