name: Build CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        java-version: 17
        distribution: 'temurin'
      - name: Build
        run: |
          ./gradlew build -x test
